{% set version = '0.6.1' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-chunked
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/chunked_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/chunked/chunked_{{ version }}.tar.gz
  sha256: 2aa28bef3f297a7eb9ae669f8ef0d0783112e69648cf1f4c20eb10d7f0dc8612

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dbi
    - r-laf
    - r-dplyr >=0.7
    - r-progress
    - r-rlang
  run:
    - r-base
    - r-dbi
    - r-laf
    - r-dplyr >=0.7
    - r-progress
    - r-rlang

test:
  commands:
    - $R -e "library('chunked')"           # [not win]
    - "\"%R%\" -e \"library('chunked')\""  # [win]

about:
  home: https://github.com/edwindj/chunked
  license: GPL-2.0-only
  summary: Data stored in text file can be processed chunkwise using 'dplyr' commands. These
    are recorded and executed per data chunk, so large files can be processed with limited
    memory using the 'LaF' package.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r


# Package: chunked
# Type: Package
# Title: Chunkwise Text-File Processing for 'dplyr'
# Version: 0.6.1
# Authors@R: c(person("Edwin", "de Jonge", email="edwindjonge@gmail.com", role=c("aut","cre"), comment = c(ORCID = "0000-0002-6580-4718")))
# Description: Data stored in text file can be processed chunkwise using 'dplyr' commands. These are recorded and executed per data chunk, so large files can be processed with limited memory using the 'LaF' package.
# License: GPL-2
# BugReports: https://github.com/edwindj/chunked/issues
# URL: https://github.com/edwindj/chunked
# Depends: dplyr (>= 0.7)
# Imports: LaF, utils, rlang, DBI, progress
# Suggests: testthat, RSQLite, dbplyr
# RoxygenNote: 7.3.3
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2025-10-02 09:03:31 UTC; edwin
# Author: Edwin de Jonge [aut, cre] (ORCID: <https://orcid.org/0000-0002-6580-4718>)
# Maintainer: Edwin de Jonge <edwindjonge@gmail.com>
# Repository: CRAN
# Date/Publication: 2025-10-02 09:50:02 UTC
